[package]
name = "ironshield-wasm"
version = "0.1.0"
edition = "2021"
authors = [ "ebosspc <software2070@protonmail.com>" ]
description = "WebAssembly bindings for the IronShield PoW system"
repository = "" # TODO: Add GitHub repository URL
license = "BUSL-1.1" # Becomes Apache-2.0 after 2028-07-24

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ironshield-core = { path = "../ironshield-core" }
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.0"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3", features = ["console"] }
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
sha2 = "0.10"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
wasm-bindgen-rayon = { version = "1.0", optional = true }
rayon = { version = "1.8", optional = true }

[features]
default = []
parallel = ["wasm-bindgen-rayon", "rayon", "ironshield-core/parallel"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
lto = true
opt-level = "z"
strip = true
codegen-units = 1 